version: '3.7'
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - {{cookiecutter.port}}:80
    depends_on:
      - server
      - client
  server:
    build:
      context: server
      dockerfile: Dockerfile
    command: python main.py
    tty: true
    volumes:
      - ./server:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
  client:
    build:
      context: client
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - './client:/app:cached'
      - './client/node_modules:/app/node_modules:cached'
    environment:
      - NODE_ENV=development
